# this file is managed by dry-rb/devtools project

name: metrics

on:
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "lib/**"
      - "*.gemspec"
      - "spec/**"
      - "Rakefile"
      - "Gemfile"
      - "Gemfile.devtools"
      - ".rubocop.yml"
      - "project.yml"
      - ".pronto.yml"
  pull_request:
    branches:
      - master
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      PRONTO_GITHUB_ACCESS_TOKEN: ${{secrets.GH_PAT}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install latest bundler
        run: |
          gem install bundler --no-document
          bundle config set without 'benchmarks docs'
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec pronto run -f github_pr_review -c origin/master