# this file is managed by dry-rb/devtools project

name: release

on:
  repository_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' && github.event.action == 'release'
    env:
      GITHUB_LOGIN: dry-bot
      GITHUB_TOKEN: ${{secrets.GH_PAT}}
      GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
      RELEASE_REPO: ${{github.event.client_payload.repo}}
      RELEASE_TAG: ${{github.event.client_payload.tag}}
      RELEASE_CREATOR: ${{github.event.client_payload.tag_creator}}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: $RELEASE_REPO
          ref: refs/tags/$RELEASE_TAG
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: |
          gem install gem-release
      - name: Set up gem credentials
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
      - name: Publish to Rubygems
        run: |
          bundle exec bin/ossy github membership $RELEASE_CREATOR dry-rb core && gem release
